import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import {
  allowedW001GeneratedSourceFiles,
  allowedW001RuntimeSourceFiles,
  findGeneratedArtifacts,
  isAllowedPreRuntimeSource,
} from "./check-generated.mjs";

test("generated artifacts and W001 runtime roots fail closed", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "hedefora-generated-"));
  try {
    await mkdir(path.join(root, "internal", "generated", "openapi"), {
      recursive: true,
    });
    await mkdir(path.join(root, "internal", "platform", "app"), {
      recursive: true,
    });
    await mkdir(path.join(root, "apps", "web", "src", "generated"), {
      recursive: true,
    });
    await writeFile(
      path.join(root, "apps", "web", "src", "generated", "placeholder.txt"),
      "fixture\n",
    );
    await mkdir(path.join(root, "api"));
    await mkdir(path.join(root, "misc"));
    await mkdir(path.join(root, "scripts"));
    await mkdir(path.join(root, "tools", "repolint"), { recursive: true });
    await writeFile(
      path.join(root, "apps", "web", "index.html"),
      "<script>window.productBehavior = true;</script>\n",
    );
    await writeFile(
      path.join(root, "apps", "web", "src", "App.tsx"),
      "export function App() { return null; }\n",
    );
    await writeFile(
      path.join(root, "apps", "web", "src", "Feature.tsx"),
      "export function Feature() { return null; }\n",
    );
    await writeFile(path.join(root, "api", "server.go"), "package api\n");
    await writeFile(path.join(root, "api", "client.generated"), "{}\n");
    await writeFile(path.join(root, "api", "client.generated.json"), "{}\n");
    await writeFile(
      path.join(root, "scripts", "check-policy.mjs"),
      "export {};\n",
    );
    await writeFile(
      path.join(root, "tools", "repolint", "new.go"),
      "package repolint\n",
    );
    const symlinkFindings = [];
    for (const fixture of [
      {
        destination: path.join(root, "apps", "web", "src", "LinkedFeature.tsx"),
        finding: "apps/web/src/LinkedFeature.tsx#symbolic-link",
        source: path.join(root, "apps", "web", "src", "App.tsx"),
        type: undefined,
      },
      {
        destination: path.join(root, "apps", "web", "src", "linked-src"),
        finding: "apps/web/src/linked-src#symbolic-link",
        source: path.join(root, "apps", "web", "src"),
        type: "dir",
      },
    ]) {
      try {
        await symlink(fixture.source, fixture.destination, fixture.type);
        symlinkFindings.push(fixture.finding);
      } catch (error) {
        if (!new Set(["EACCES", "EPERM"]).has(error?.code)) throw error;
      }
    }
    await writeFile(
      path.join(root, "misc", "client.generated.ts"),
      "export {};\n",
    );
    await writeFile(
      path.join(root, "misc", "marker.go"),
      "// Code generated by fixture. DO NOT EDIT.\npackage fixture\n",
    );
    await writeFile(
      path.join(root, "internal", "generated", "openapi", "openapi.gen.go"),
      "// Code generated by HedefOra sealed OpenAPI renderer. DO NOT EDIT.\npackage openapi\n",
    );
    await writeFile(
      path.join(root, "internal", "generated", "openapi", "extra.gen.go"),
      "package openapi\n",
    );
    await writeFile(
      path.join(root, "internal", "platform", "app", "app.go"),
      "package app\n",
    );

    const expectedFindings = [
      "api/client.generated",
      "api/client.generated.json",
      "api/server.go#unexpected-source",
      "apps/web/index.html#inline-behavior",
      "apps/web/src/Feature.tsx#unexpected-source",
      "apps/web/src/generated",
      "internal/generated/openapi/extra.gen.go#unexpected-runtime-source",
      "internal/platform/app/app.go#unexpected-runtime-source",
      "misc/client.generated.ts",
      "misc/marker.go#generated-marker",
      ...symlinkFindings,
    ].sort();
    assert.deepEqual(await findGeneratedArtifacts(root), expectedFindings);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("only the two exact W001 supply-chain Go tool files are allowed", async () => {
  const root = await mkdtemp(
    path.join(os.tmpdir(), "hedefora-w001-tool-source-"),
  );
  try {
    const toolRoot = path.join(
      root,
      "tools",
      "osvdbcheck",
      "cmd",
      "osvdbcheck",
    );
    await mkdir(toolRoot, { recursive: true });
    await mkdir(path.join(root, "tools", "osvdbcheck", "cmd", "other"), {
      recursive: true,
    });
    await writeFile(path.join(toolRoot, "main.go"), "package main\n");
    await writeFile(path.join(toolRoot, "main_test.go"), "package main\n");
    await writeFile(path.join(toolRoot, "helper.go"), "package main\n");
    await writeFile(
      path.join(root, "tools", "osvdbcheck", "cmd", "other", "main.go"),
      "package main\n",
    );

    assert.deepEqual(await findGeneratedArtifacts(root), [
      "tools/osvdbcheck/cmd/osvdbcheck/helper.go#unexpected-source",
      "tools/osvdbcheck/cmd/other/main.go#unexpected-source",
    ]);
    assert.equal(
      isAllowedPreRuntimeSource("tools/osvdbcheck/cmd/osvdbcheck/main.go"),
      true,
    );
    assert.equal(
      isAllowedPreRuntimeSource("tools/osvdbcheck/cmd/osvdbcheck/Main.go"),
      false,
    );

    await writeFile(
      path.join(toolRoot, "main.go"),
      "// Code generated by fixture. DO NOT EDIT.\npackage main\n",
    );
    assert.deepEqual(await findGeneratedArtifacts(root), [
      "tools/osvdbcheck/cmd/osvdbcheck/helper.go#unexpected-source",
      "tools/osvdbcheck/cmd/osvdbcheck/main.go#generated-marker",
      "tools/osvdbcheck/cmd/other/main.go#unexpected-source",
    ]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("only the exact sealed OpenAPI generated file is allowlisted", () => {
  assert.deepEqual(
    [...allowedW001GeneratedSourceFiles],
    ["internal/generated/openapi/openapi.gen.go"],
  );
  assert.equal(
    isAllowedPreRuntimeSource("internal/generated/openapi/openapi.gen.go"),
    true,
  );
  assert.equal(
    isAllowedPreRuntimeSource("internal/generated/openapi/OpenAPI.gen.go"),
    false,
  );
  assert.equal(
    isAllowedPreRuntimeSource("internal/generated/openapi/extra.gen.go"),
    false,
  );
});

test("only the exact T04D runtime source set is allowlisted", () => {
  assert.deepEqual(
    [...allowedW001RuntimeSourceFiles],
    [
      "cmd/hedefora/main.go",
      "cmd/hedefora/main_test.go",
      "internal/platform/app/api.go",
      "internal/platform/app/api_test.go",
      "internal/platform/config/api.go",
      "internal/platform/config/api_test.go",
      "internal/platform/health/service.go",
      "internal/platform/health/service_test.go",
      "internal/platform/http/handler.go",
      "internal/platform/http/handler_test.go",
      "internal/platform/http/server.go",
      "internal/platform/http/server_test.go",
      "internal/platform/telemetry/telemetry.go",
      "internal/platform/telemetry/telemetry_test.go",
    ],
  );
  for (const source of allowedW001RuntimeSourceFiles) {
    assert.equal(isAllowedPreRuntimeSource(source), true, source);
  }
  for (const source of [
    "cmd/hedefora/Main.go",
    "cmd/hedefora/worker.go",
    "internal/platform/http/middleware.go",
    "internal/platform/postgres/postgres.go",
  ]) {
    assert.equal(isAllowedPreRuntimeSource(source), false, source);
  }
});

test("the cmd runtime root rejects every non-allowlisted file independent of extension", async () => {
  const root = await mkdtemp(
    path.join(os.tmpdir(), "hedefora-runtime-command-boundary-"),
  );
  try {
    const commandRoot = path.join(root, "cmd", "hedefora");
    await mkdir(commandRoot, { recursive: true });
    await writeFile(path.join(commandRoot, "main.go"), "package main\n");
    await writeFile(path.join(commandRoot, "main_test.go"), "package main\n");

    const rejectedFiles = [
      "assembly-lower.s",
      "assembly-upper.S",
      "extensionless",
      "object.syso",
      "payload.bin",
    ];
    for (const filename of rejectedFiles) {
      await writeFile(path.join(commandRoot, filename), "fixture\n");
    }

    assert.deepEqual(
      await findGeneratedArtifacts(root),
      rejectedFiles
        .map((filename) => `cmd/hedefora/${filename}#unexpected-runtime-source`)
        .sort(),
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("ignored cmd files cannot bypass the exact runtime source boundary", async () => {
  const root = await mkdtemp(
    path.join(os.tmpdir(), "hedefora-ignored-runtime-command-"),
  );
  try {
    runGit(root, "init", "--quiet");
    const commandRoot = path.join(root, "cmd", "hedefora");
    await mkdir(commandRoot, { recursive: true });
    await writeFile(path.join(root, ".gitignore"), "cmd/hedefora/ignored-*\n");
    await writeFile(
      path.join(commandRoot, "main.go"),
      'package main\n\nimport _ "embed"\n\n//go:embed ignored-embedded.bin\nvar embedded []byte\n\nfunc main() {}\n',
    );
    await writeFile(path.join(commandRoot, "main_test.go"), "package main\n");

    const ignoredFiles = [
      "ignored-assembly.s",
      "ignored-embedded.bin",
      "ignored-extensionless",
      "ignored-object.syso",
    ];
    for (const filename of ignoredFiles) {
      await writeFile(path.join(commandRoot, filename), "fixture\n");
    }
    const symlinkFindings = [];
    try {
      await symlink(
        path.join(commandRoot, "main.go"),
        path.join(commandRoot, "ignored-link.s"),
      );
      symlinkFindings.push("cmd/hedefora/ignored-link.s#symbolic-link");
    } catch (error) {
      if (!new Set(["EACCES", "EPERM"]).has(error?.code)) throw error;
    }
    runGit(
      root,
      "add",
      ".gitignore",
      "cmd/hedefora/main.go",
      "cmd/hedefora/main_test.go",
    );

    assert.deepEqual(
      await findGeneratedArtifacts(root),
      [
        ...ignoredFiles.map(
          (filename) => `cmd/hedefora/${filename}#unexpected-runtime-source`,
        ),
        ...symlinkFindings,
      ].sort(),
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("force-tracked source in ignored output directories fails closed", async () => {
  const root = await mkdtemp(
    path.join(os.tmpdir(), "hedefora-tracked-output-"),
  );
  try {
    runGit(root, "init", "--quiet");
    const outputDirectories = [
      ".cache",
      ".pnpm-store",
      "artifacts",
      "build",
      "coverage",
      "dist",
      "node_modules",
    ];
    await writeFile(
      path.join(root, ".gitignore"),
      `${outputDirectories.map((directory) => `${directory}/`).join("\n")}\n`,
    );
    runGit(root, "add", ".gitignore");
    for (const directory of outputDirectories) {
      await mkdir(path.join(root, directory), { recursive: true });
      await writeFile(
        path.join(root, directory, "feature.js"),
        "export const feature = true;\n",
      );
      runGit(root, "add", "--force", `${directory}/feature.js`);
    }
    await writeFile(
      path.join(root, "dist", "ignored-untracked.js"),
      "export const ignored = true;\n",
    );
    await mkdir(path.join(root, "misc"));
    await writeFile(
      path.join(root, "misc", "Feature.TSX"),
      "export function Feature() { return null; }\n",
    );
    await writeFile(
      path.join(root, "misc", "marker.GO"),
      "// Code generated by fixture. DO NOT EDIT.\npackage fixture\n",
    );
    await writeFile(
      path.join(root, "misc", "index.HTML"),
      '<button onclick="window.run()">Run</button>\n',
    );
    runGit(
      root,
      "add",
      "misc/Feature.TSX",
      "misc/marker.GO",
      "misc/index.HTML",
    );

    assert.deepEqual(await findGeneratedArtifacts(root), [
      ".cache/feature.js#unexpected-source",
      ".pnpm-store/feature.js#unexpected-source",
      "artifacts/feature.js#unexpected-source",
      "build/feature.js#unexpected-source",
      "coverage/feature.js#unexpected-source",
      "dist/feature.js#unexpected-source",
      "misc/Feature.TSX#unexpected-source",
      "misc/index.HTML#inline-behavior",
      "misc/marker.GO#generated-marker",
      "node_modules/feature.js#unexpected-source",
    ]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

function runGit(root, ...arguments_) {
  const result = spawnSync("git", ["-C", root, ...arguments_], {
    encoding: "utf8",
  });
  assert.equal(
    result.status,
    0,
    `git ${arguments_.join(" ")} failed: ${result.stderr || result.error?.message}`,
  );
}
