import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { mkdir, mkdtemp, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { findGeneratedArtifacts } from "./check-generated.mjs";

test("generated artifacts and W001 runtime roots fail closed", async () => {
  const root = await mkdtemp(path.join(os.tmpdir(), "hedefora-generated-"));
  try {
    await mkdir(path.join(root, "internal"));
    await mkdir(path.join(root, "apps", "web", "src", "generated"), {
      recursive: true,
    });
    await writeFile(
      path.join(root, "apps", "web", "src", "generated", "placeholder.txt"),
      "fixture\n",
    );
    await mkdir(path.join(root, "api"));
    await mkdir(path.join(root, "misc"));
    await mkdir(path.join(root, "scripts"));
    await mkdir(path.join(root, "tools", "repolint"), { recursive: true });
    await writeFile(
      path.join(root, "apps", "web", "index.html"),
      "<script>window.productBehavior = true;</script>\n",
    );
    await writeFile(
      path.join(root, "apps", "web", "src", "App.tsx"),
      "export function App() { return null; }\n",
    );
    await writeFile(
      path.join(root, "apps", "web", "src", "Feature.tsx"),
      "export function Feature() { return null; }\n",
    );
    await writeFile(path.join(root, "api", "server.go"), "package api\n");
    await writeFile(path.join(root, "api", "client.generated"), "{}\n");
    await writeFile(path.join(root, "api", "client.generated.json"), "{}\n");
    await writeFile(
      path.join(root, "scripts", "check-policy.mjs"),
      "export {};\n",
    );
    await writeFile(
      path.join(root, "tools", "repolint", "new.go"),
      "package repolint\n",
    );
    await symlink(
      path.join(root, "apps", "web", "src", "App.tsx"),
      path.join(root, "apps", "web", "src", "LinkedFeature.tsx"),
    );
    await symlink(
      path.join(root, "apps", "web", "src"),
      path.join(root, "apps", "web", "src", "linked-src"),
      "dir",
    );
    await writeFile(
      path.join(root, "misc", "client.generated.ts"),
      "export {};\n",
    );
    await writeFile(
      path.join(root, "misc", "marker.go"),
      "// Code generated by fixture. DO NOT EDIT.\npackage fixture\n",
    );

    assert.deepEqual(await findGeneratedArtifacts(root), [
      "api/client.generated",
      "api/client.generated.json",
      "api/server.go#unexpected-source",
      "apps/web/index.html#inline-behavior",
      "apps/web/src/Feature.tsx#unexpected-source",
      "apps/web/src/LinkedFeature.tsx#symbolic-link",
      "apps/web/src/generated",
      "apps/web/src/linked-src#symbolic-link",
      "internal",
      "misc/client.generated.ts",
      "misc/marker.go#generated-marker",
    ]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("force-tracked source in ignored output directories fails closed", async () => {
  const root = await mkdtemp(
    path.join(os.tmpdir(), "hedefora-tracked-output-"),
  );
  try {
    runGit(root, "init", "--quiet");
    const outputDirectories = [
      ".cache",
      ".pnpm-store",
      "artifacts",
      "build",
      "coverage",
      "dist",
      "node_modules",
    ];
    await writeFile(
      path.join(root, ".gitignore"),
      `${outputDirectories.map((directory) => `${directory}/`).join("\n")}\n`,
    );
    runGit(root, "add", ".gitignore");
    for (const directory of outputDirectories) {
      await mkdir(path.join(root, directory), { recursive: true });
      await writeFile(
        path.join(root, directory, "feature.js"),
        "export const feature = true;\n",
      );
      runGit(root, "add", "--force", `${directory}/feature.js`);
    }

    assert.deepEqual(await findGeneratedArtifacts(root), [
      ".cache/feature.js#unexpected-source",
      ".pnpm-store/feature.js#unexpected-source",
      "artifacts/feature.js#unexpected-source",
      "build/feature.js#unexpected-source",
      "coverage/feature.js#unexpected-source",
      "dist/feature.js#unexpected-source",
      "node_modules/feature.js#unexpected-source",
    ]);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

function runGit(root, ...arguments_) {
  const result = spawnSync("git", ["-C", root, ...arguments_], {
    encoding: "utf8",
  });
  assert.equal(
    result.status,
    0,
    `git ${arguments_.join(" ")} failed: ${result.stderr || result.error?.message}`,
  );
}
