import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { spawnSync } from "node:child_process";
import {
  copyFile,
  link,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  rm,
  stat,
  symlink,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { generatorNegativeMutations } from "./fixtures/openapi-generator-negative-mutations.mjs";
import {
  GeneratorError,
  canonicalContractRelativePath,
  checkGeneratedArtifact,
  expectedContractBytes,
  expectedContractSha256,
  generateArtifactFromSource,
  generatedArtifactRelativePath,
  parseGeneratorMode,
  writeGeneratedArtifact,
} from "./generate-openapi.mjs";
import { negativeMutations } from "./fixtures/openapi-negative-mutations.mjs";
import { applySingleMutation } from "./validate-contracts.mjs";

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url));
const repositoryRoot = path.resolve(scriptDirectory, "..");
const generatorPath = path.join(scriptDirectory, "generate-openapi.mjs");
const canonicalSource = await readFile(
  path.join(repositoryRoot, ...canonicalContractRelativePath.split("/")),
);
const expectedArtifactSha256 =
  "d5dbb7623e3c9603be2f580ccae07600fa3f86df8b03a740f9a1c9a068a872bd";

test("sealed source produces one deterministic, reviewed Go artifact", () => {
  assert.equal(canonicalSource.length, expectedContractBytes);
  assert.equal(sha256(canonicalSource), expectedContractSha256);

  const first = generateArtifactFromSource(canonicalSource);
  const second = generateArtifactFromSource(Buffer.from(canonicalSource));
  assert.equal(first.relativePath, generatedArtifactRelativePath);
  assert.equal(first.sourceSha256, expectedContractSha256);
  assert.equal(first.sha256, expectedArtifactSha256);
  assert.deepEqual(first.bytes, second.bytes);

  const generated = first.bytes.toString("utf8");
  assert.ok(generated.endsWith("\n"));
  assert.equal(generated.includes("\r"), false);
  assert.match(
    generated,
    /Code generated by HedefOra sealed OpenAPI renderer\. DO NOT EDIT\./u,
  );
  assert.match(generated, /type RequestID string/u);
  assert.match(generated, /type HealthLiveResponse struct/u);
  assert.match(generated, /type ErrorEnvelope struct/u);
  assert.match(generated, /type ServiceUnavailableError struct/u);
  assert.match(generated, /type StrictServerInterface interface/u);
  assert.match(
    generated,
    /GetHealthLive\(context\.Context, GetHealthLiveRequestObject\) \(GetHealthLiveResponseObject, error\)/u,
  );
  assert.equal(
    [...generated.matchAll(/ErrorCode[A-Za-z]+\s+ErrorCode =/gu)].length,
    7,
  );
  assert.doesNotMatch(
    generated,
    /(?:\/\/go:|#cgo|go:linkname|\bunsafe\b|os\/exec|net\/http|fixture-canary)/u,
  );
});

test("all canonical one-mutation contract fixtures are rejected", () => {
  const source = canonicalSource.toString("utf8");
  for (const mutation of negativeMutations) {
    const mutated = Buffer.from(applySingleMutation(source, mutation), "utf8");
    assert.throws(
      () => generateArtifactFromSource(mutated),
      (error) =>
        error instanceof GeneratorError &&
        typeof error.code === "string" &&
        error.code.startsWith("SOURCE_"),
      mutation.name,
    );
  }
});

test("generator-specific parser, reference and code-poison mutations reject", () => {
  const source = canonicalSource.toString("utf8");
  for (const mutation of generatorNegativeMutations) {
    const mutated = Buffer.from(applySingleMutation(source, mutation), "utf8");
    assert.throws(
      () => generateArtifactFromSource(mutated),
      (error) =>
        error instanceof GeneratorError && error.code === mutation.code,
      mutation.name,
    );
  }
});

test("encoding and resource limits reject before generation", () => {
  const cases = [
    Buffer.from([0xc3, 0x28]),
    Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), canonicalSource]),
    Buffer.concat([canonicalSource, Buffer.from("\0")]),
    Buffer.from(canonicalSource.toString("utf8").replace("\n", "\r\n")),
    Buffer.from(canonicalSource.toString("utf8").replace("  title", "\ttitle")),
    Buffer.alloc(64 * 1024 + 1, 0x61),
  ];
  for (const source of cases) {
    assert.throws(
      () => generateArtifactFromSource(source),
      (error) => error instanceof GeneratorError,
    );
  }
});

test("filesystem reads enforce source and output byte limits before mutation", async () => {
  const oversizedSourceRoot = await createFixtureRepository(
    Buffer.alloc(64 * 1024 + 1, 0x61),
  );
  const oversizedOutputRoot = await createFixtureRepository();
  try {
    await assert.rejects(
      writeGeneratedArtifact(oversizedSourceRoot),
      (error) =>
        error instanceof GeneratorError && error.code === "SOURCE_SIZE_INVALID",
    );
    await assert.rejects(
      readdir(path.join(oversizedSourceRoot, "internal")),
      (error) => error?.code === "ENOENT",
    );

    await writeGeneratedArtifact(oversizedOutputRoot);
    const artifactPath = fixturePath(
      oversizedOutputRoot,
      generatedArtifactRelativePath,
    );
    const oversizedOutput = Buffer.alloc(32 * 1024 + 1, 0x62);
    await writeFile(artifactPath, oversizedOutput);
    const beforeDigest = sha256(await readFile(artifactPath));

    for (const operation of [checkGeneratedArtifact, writeGeneratedArtifact]) {
      await assert.rejects(
        operation(oversizedOutputRoot),
        (error) =>
          error instanceof GeneratorError &&
          error.code === "OUTPUT_LIMIT_EXCEEDED",
      );
      assert.equal(sha256(await readFile(artifactPath)), beforeDigest);
    }
  } finally {
    await rm(oversizedSourceRoot, { recursive: true, force: true });
    await rm(oversizedOutputRoot, { recursive: true, force: true });
  }
});

test("CLI accepts only one fixed mode and exposes no path override", () => {
  assert.equal(parseGeneratorMode(["--check"]), "--check");
  assert.equal(parseGeneratorMode(["--write"]), "--write");
  for (const arguments_ of [
    [],
    ["--output", "fixture"],
    ["--input=fixture"],
    ["--write", "--check"],
    ["--template=fixture"],
  ]) {
    assert.throws(
      () => parseGeneratorMode(arguments_),
      (error) =>
        error instanceof GeneratorError && error.code === "INVALID_ARGUMENTS",
    );
  }
  assert.equal(path.isAbsolute(generatedArtifactRelativePath), false);
  assert.equal(generatedArtifactRelativePath.split("/").includes(".."), false);
});

test("write/check is deterministic, drift-sensitive and inventory-closed", async () => {
  const root = await createFixtureRepository();
  try {
    const first = await writeGeneratedArtifact(root);
    assert.equal(first.changed, true);
    assert.equal(first.sha256, expectedArtifactSha256);

    const artifactPath = fixturePath(root, generatedArtifactRelativePath);
    const beforeCheck = await stat(artifactPath);
    const checked = await checkGeneratedArtifact(root);
    const afterCheck = await stat(artifactPath);
    assert.equal(checked.sha256, expectedArtifactSha256);
    assert.equal(afterCheck.mtimeMs, beforeCheck.mtimeMs);

    const unchanged = await writeGeneratedArtifact(root);
    assert.equal(unchanged.changed, false);
    await writeFile(artifactPath, "package drift\n");
    await assert.rejects(
      checkGeneratedArtifact(root),
      (error) =>
        error instanceof GeneratorError && error.code === "GENERATED_DRIFT",
    );

    const replaced = await writeGeneratedArtifact(root);
    assert.equal(replaced.changed, true);
    assert.equal(sha256(await readFile(artifactPath)), expectedArtifactSha256);

    await writeFile(path.join(path.dirname(artifactPath), "unexpected.go"), "");
    await assert.rejects(
      checkGeneratedArtifact(root),
      (error) =>
        error instanceof GeneratorError &&
        error.code === "OUTPUT_INVENTORY_INVALID",
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("rejected source creates no output tree and never echoes code poison", async () => {
  const source = canonicalSource.toString("utf8");
  const poison = generatorNegativeMutations.find(
    ({ name }) => name === "reject-operation-id-code-poison",
  );
  const root = await createFixtureRepository(
    Buffer.from(applySingleMutation(source, poison), "utf8"),
  );
  try {
    await assert.rejects(
      writeGeneratedArtifact(root),
      (error) =>
        error instanceof GeneratorError && error.code.startsWith("SOURCE_"),
    );
    await assert.rejects(
      readdir(path.join(root, "internal")),
      (error) => error?.code === "ENOENT",
    );

    await copyGenerator(root);
    const child = runGenerator(root, "--write", {
      SOURCE_DATE_EPOCH: "fixture-canary",
    });
    assert.equal(child.status, 1);
    assert.match(
      child.stderr,
      /^ERROR: sealed OpenAPI renderer failed \(SOURCE_/u,
    );
    assert.equal(child.stderr.includes("fixture-canary"), false);
    assert.equal(child.stderr.includes("go:generate"), false);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("fresh processes in different roots and environments produce equal bytes", async () => {
  const roots = [
    await createFixtureRepository(),
    await createFixtureRepository(),
  ];
  try {
    const results = [];
    for (const [index, root] of roots.entries()) {
      await copyGenerator(root);
      const child = runGenerator(root, "--write", {
        LANG: index === 0 ? "C" : "tr_TR.UTF-8",
        SOURCE_DATE_EPOCH: index === 0 ? "0" : "2147483647",
        TZ: index === 0 ? "UTC" : "Europe/Istanbul",
      });
      assert.equal(child.status, 0, child.stderr);
      const bytes = await readFile(
        fixturePath(root, generatedArtifactRelativePath),
      );
      results.push(bytes);
    }
    assert.deepEqual(results[0], results[1]);
    assert.equal(sha256(results[0]), expectedArtifactSha256);
  } finally {
    await Promise.all(
      roots.map((root) => rm(root, { recursive: true, force: true })),
    );
  }
});

test("single-linked input and output files are mandatory", async () => {
  const inputRoot = await mkdtemp(
    path.join(os.tmpdir(), "hedefora-gen-link-in-"),
  );
  const outputRoot = await createFixtureRepository();
  try {
    const actualSource = path.join(inputRoot, "actual.yaml");
    const linkedSource = fixturePath(inputRoot, canonicalContractRelativePath);
    await mkdir(path.dirname(linkedSource), { recursive: true });
    await writeFile(actualSource, canonicalSource);
    await link(actualSource, linkedSource);
    await assert.rejects(
      writeGeneratedArtifact(inputRoot),
      (error) =>
        error instanceof GeneratorError &&
        error.code === "INPUT_BOUNDARY_INVALID",
    );

    await writeGeneratedArtifact(outputRoot);
    const artifactPath = fixturePath(outputRoot, generatedArtifactRelativePath);
    const sentinelPath = path.join(outputRoot, "sentinel.go");
    const sentinel = Buffer.from("package sentinel\n");
    await writeFile(sentinelPath, sentinel);
    await rm(artifactPath);
    await link(sentinelPath, artifactPath);
    await assert.rejects(
      checkGeneratedArtifact(outputRoot),
      (error) =>
        error instanceof GeneratorError &&
        error.code === "OUTPUT_BOUNDARY_INVALID",
    );
    assert.deepEqual(await readFile(sentinelPath), sentinel);
  } finally {
    await rm(inputRoot, { recursive: true, force: true });
    await rm(outputRoot, { recursive: true, force: true });
  }
});

test("linked output ancestor is rejected without touching its target", async (t) => {
  const root = await createFixtureRepository();
  const outside = await mkdtemp(
    path.join(os.tmpdir(), "hedefora-gen-outside-"),
  );
  try {
    await mkdir(path.join(root, "internal", "generated"), { recursive: true });
    const linkedDirectory = path.join(root, "internal", "generated", "openapi");
    try {
      await symlink(
        outside,
        linkedDirectory,
        process.platform === "win32" ? "junction" : "dir",
      );
    } catch (error) {
      if (new Set(["EACCES", "EPERM"]).has(error?.code)) {
        t.skip("this local platform cannot create the link fixture");
        return;
      }
      throw error;
    }
    await assert.rejects(
      writeGeneratedArtifact(root),
      (error) =>
        error instanceof GeneratorError &&
        error.code === "OUTPUT_BOUNDARY_INVALID",
    );
    assert.deepEqual(await readdir(outside), []);
  } finally {
    await rm(root, { recursive: true, force: true });
    await rm(outside, { recursive: true, force: true });
  }
});

test("stale temporary output fails closed without a partial target", async () => {
  const root = await createFixtureRepository();
  try {
    const outputDirectory = path.dirname(
      fixturePath(root, generatedArtifactRelativePath),
    );
    await mkdir(outputDirectory, { recursive: true });
    await writeFile(
      path.join(outputDirectory, ".openapi.gen.go.hedefora.tmp"),
      "stale",
    );
    await assert.rejects(
      writeGeneratedArtifact(root),
      (error) =>
        error instanceof GeneratorError &&
        error.code === "OUTPUT_INVENTORY_INVALID",
    );
    await assert.rejects(
      readFile(fixturePath(root, generatedArtifactRelativePath)),
      (error) => error?.code === "ENOENT",
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

async function createFixtureRepository(source = canonicalSource) {
  const root = await mkdtemp(path.join(os.tmpdir(), "hedefora-openapi-gen-"));
  const contractPath = fixturePath(root, canonicalContractRelativePath);
  await mkdir(path.dirname(contractPath), { recursive: true });
  await writeFile(contractPath, source);
  return root;
}

async function copyGenerator(root) {
  const destination = path.join(root, "scripts", "generate-openapi.mjs");
  await mkdir(path.dirname(destination), { recursive: true });
  await copyFile(generatorPath, destination);
}

function runGenerator(root, mode, environment = {}) {
  return spawnSync(
    process.execPath,
    [path.join(root, "scripts", "generate-openapi.mjs"), mode],
    {
      cwd: path.dirname(root),
      encoding: "utf8",
      env: childEnvironment(environment),
      timeout: 10_000,
      windowsHide: true,
    },
  );
}

function childEnvironment(overrides) {
  const environment = { ...overrides };
  for (const name of ["ComSpec", "PATHEXT", "SystemRoot", "TEMP", "TMP"]) {
    if (process.env[name] !== undefined) environment[name] = process.env[name];
  }
  return environment;
}

function fixturePath(root, relativePath) {
  return path.join(root, ...relativePath.split("/"));
}

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}
